version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      dev-deps:
        patterns: ['@types/*', 'typescript', 'vitest', '@vitest/*', 'eslint', '@typescript-eslint/*']
